# Generated by Django 3.2 on 2023-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='includes',
            field=models.ManyToManyField(blank=True, related_name='includes', to='places.FoodPackageItem'),
        ),
    ]
