# Generated by Django 2.2.14 on 2022-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='places/logo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('hotspot', 'hotspot'), ('offline', 'offline'), ('website', 'hotspot')], default='hotspot:web:business:default', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('on-route', 'On Route'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
