# Generated by Django 2.2.14 on 2022-12-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221125_1254'),
        ('places', '0002_auto_20221125_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='customers',
            field=models.ManyToManyField(blank=True, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, default='hotspot:admin:web', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('on-route', 'On Route'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
