# Generated by Django 3.2 on 2023-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_initial'),
        ('places', '0003_auto_20230422_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='reviews',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='metrics.Review'),
        ),
    ]
