# Generated by Django 3.2 on 2023-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20230529_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranch',
            name='branch_name',
            field=models.CharField(blank=True, default='Main Branch', max_length=100, unique=True),
        ),
    ]
