# Generated by Django 2.2.14 on 2023-01-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_buyercart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, default='web:hotspot', max_length=20, null=True),
        ),
    ]
