# Generated by Django 3.2 on 2023-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_restaurantbranch_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='tags',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, to='places.Category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='places.Tag'),
        ),
    ]
