# Generated by Django 2.2.14 on 2023-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20230125_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
