# Generated by Django 3.2 on 2023-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_restaurantstaff_assigned_branches'),
        ('places', '0006_auto_20230531_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='staff',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='orders',
            field=models.ManyToManyField(blank=True, to='places.Order'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to='accounts.RestaurantStaff'),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='accounts.RestaurantStaff'),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='related_orders',
            field=models.ManyToManyField(blank=True, related_name='related_orders', to='places.Order'),
        ),
    ]
