# Generated by Django 2.2.14 on 2023-02-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230201_1656'),
        ('places', '0006_order_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmessage',
            old_name='msg_type',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='billing_plan',
            field=models.CharField(default='free-trial', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(blank=True, default='NG', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(blank=True, default='NGN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='current_billing_period',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fulfilment',
            field=models.CharField(default='out-sourced', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='domian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='next_billing_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offer_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offer_dine_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offer_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='store_mode',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_type', models.CharField(choices=[('Flat', 'flat'), ('Percentage', 'percentage')], default='flat', max_length=10)),
                ('selector_target', models.CharField(blank=True, default='id', max_length=50)),
                ('selector_value', models.CharField(blank=True, max_length=100, null=True)),
                ('redeemers', models.ManyToManyField(blank=True, to='accounts.Customer')),
                ('related_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Restaurant')),
            ],
        ),
    ]
