# Generated by Django 3.2 on 2023-06-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20230602_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.restaurantbranch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.restaurant'),
        ),
    ]
