# Generated by Django 3.2 on 2023-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20230603_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='branch_quota',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_quota',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='staff_quota',
            field=models.IntegerField(default=2),
        ),
    ]
