# Generated by Django 3.2 on 2023-06-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20230605_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbranch',
            name='inherit_menu_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.restaurantbranch'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='overdraft_items',
            field=models.ManyToManyField(blank=True, related_name='overdraft_items', to='places.FoodItem'),
        ),
    ]
