# Generated by Django 3.2 on 2023-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20230605_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranch',
            name='delivery_fulfilment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
