# Generated by Django 3.2 on 2023-06-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_restaurantbranch_delivery_fulfilment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantbranch',
            old_name='is_live_mode',
            new_name='is_live',
        ),
    ]
