# Generated by Django 3.2 on 2023-06-09 12:17

from django.db import migrations, models
import places.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_rename_is_live_mode_restaurantbranch_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=places.models.orders.generate_invoice_id, max_length=12, unique=True),
        ),
    ]
