# Generated by Django 3.2 on 2023-06-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_billingmethod_owner'),
        ('places', '0013_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='billing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.billingmethod'),
        ),
    ]
