# Generated by Django 3.2 on 2023-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_restaurant_billing_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='current_billing_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
