# Generated by Django 3.2 on 2023-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_restaurant_current_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, to='places.FoodItem'),
        ),
    ]
