# Generated by Django 3.2 on 2023-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
