# Generated by Django 3.2 on 2023-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_order_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='featured_items',
            field=models.ManyToManyField(blank=True, related_name='featured_items', to='places.FoodItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('on-route', 'On Route'), ('delivered', 'Delivered'), ('picked-up', 'Picked Up')], default='pending', max_length=20),
        ),
    ]
