# Generated by Django 3.2 on 2023-07-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20230617_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantbranch',
            options={'verbose_name_plural': 'Restaurant Branches'},
        ),
    ]
