# Generated by Django 3.2 on 2023-07-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_restaurantbranch_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmessage',
            old_name='to',
            new_name='place_id',
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='branch_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.restaurantbranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
            preserve_default=False,
        ),
    ]
