# Generated by Django 3.2 on 2023-09-16 07:20

from django.db import migrations, models
import django.db.models.deletion
import places.utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('name_on_card', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('card_number', models.CharField(max_length=16)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cvc', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=70, null=True)),
                ('webhook_endpoint', models.URLField(blank=True, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('instance_id', models.CharField(max_length=200, unique=True)),
                ('app_id', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=150)),
                ('bank_code', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('staff_id', models.CharField(default=places.utils.helpers.generate_staff_id, max_length=20)),
                ('branch_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('priority', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(default='Kaduna', max_length=100)),
                ('city', models.CharField(default='Kaduna', max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantStaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('permissions', models.ManyToManyField(blank=True, related_name='perms', to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
