# Generated by Django 3.2 on 2023-04-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_fooditem_includes'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessAccount',
            new_name='Merchant',
        ),
    ]
