# Generated by Django 3.2 on 2023-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20230529_1908'),
        ('accounts', '0003_rename_businessaccount_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantstaff',
            name='assigned_branches',
            field=models.ManyToManyField(related_name='assigned_branches', to='places.RestaurantBranch'),
        ),
    ]
