# Generated by Django 3.2 on 2023-06-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20230602_1557'),
        ('accounts', '0004_restaurantstaff_assigned_branches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInformation',
            new_name='PayoutInformation',
        ),
        migrations.RemoveField(
            model_name='restaurantstaff',
            name='assigned_branches',
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_branches', to='places.restaurantbranch'),
        ),
        migrations.AddField(
            model_name='restaurantstaff',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('site-manager', 'Site Manager')], max_length=100, null=True),
        ),
    ]
