# Generated by Django 2.2.14 on 2022-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20221125_1130'),
        ('accounts', '0004_auto_20220927_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='following',
            new_name='follows',
        ),
        migrations.AddField(
            model_name='customer',
            name='liked_tags',
            field=models.ManyToManyField(blank=True, to='places.Tag'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_app_user',
            field=models.BooleanField(default=False),
        ),
    ]
