# Generated by Django 3.2 on 2023-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230603_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantstaff',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('site-manager', 'Site Manager'), ('superuser', 'Superuser')], max_length=100, null=True),
        ),
    ]
