# Generated by Django 2.2.14 on 2022-11-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221125_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_app_user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='liked_tags',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
    ]
