# Generated by Django 3.2 on 2023-06-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_restaurantstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmethod',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.merchant'),
        ),
    ]
