# Generated by Django 2.2.14 on 2023-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_buyercart'),
        ('accounts', '0007_remove_customer_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='carts',
            field=models.ManyToManyField(blank=True, to='places.BuyerCart'),
        ),
    ]
