# Generated by Django 3.2 on 2023-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_billingmethod_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
