# Generated by Django 3.2 on 2023-07-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_restaurantbranch_options'),
        ('accounts', '0008_usernotification_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.restaurantbranch')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.restaurant')),
            ],
        ),
    ]
