# Generated by Django 2.2.14 on 2023-02-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_order_invoice'),
        ('accounts', '0008_customer_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='msg_type',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='usernotification',
            old_name='to',
            new_name='user',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingmethod',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.Restaurant'),
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=150)),
                ('bank_code', models.CharField(max_length=150)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=70, null=True)),
                ('webhook_endpoint', models.URLField(blank=True, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('instance_id', models.CharField(max_length=200, unique=True)),
                ('app_id', models.CharField(max_length=200, unique=True)),
                ('related_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Restaurant')),
            ],
        ),
    ]
