# Generated by Django 3.2 on 2023-07-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_storenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreNotification',
        ),
    ]
